function [ key ] = globalindices2key( index )
%GLOBALINDICES2KEY convert indices to a global key for container.Map
%   [ key ] = globalindices2key( index ) converts global index ( a struct)
%   into a string key for containers.Map usage.

key =   [ ...
            index.imgtoken, '_', ...
            num2str(index.resolution), '_', ...
            num2str(index.xoffset), '_', ...
            num2str(index.yoffset), '_', ...
            num2str(index.zoffset), '_', ...
            num2str(index.xsize), '_', ...
            num2str(index.ysize), '_', ...
            '[', indices2key(index.zslice1, index.zslice2), ']', ...
        ];

end
