function [ key ] = globalindices2key( index )
%GLOBALINDICES2KEY convert indices to a global key for container.Map
%   [ key ] = globalindices2key( index ) converts global index, a structure,
%   into a string key for containers.Map usage.

key =   [ ...
            num2str(index.resolution), '_', ...
            num2str(index.xoffset), '_', ...
            num2str(index.yoffset), '_', ...
            num2str(index.zoffset), '_', ...
            num2str(index.xsubsize), '_', ...
            num2str(index.ysubsize), '_', ...
            localindices2key(index.zslice1, index.zslice2) ...
        ];

end
